"use server";

import transporter from "../lib/nodemailer"; // adjust path if needed

interface OrderItem {
  name: string;
  quantity: number;
  price: number;
}

interface SendReceiptParams {
  to: string;
  orderId: number;
  orderItems: OrderItem[];
  total: number;
  description?: string;
  link?: string;
}

export async function sendReceiptAction({
  to,
  orderId,
  orderItems,
  total,
  description = "Thank you for your purchase! Here is your receipt.",
  link,
}: SendReceiptParams) {
  const itemsHTML = orderItems
    .map(
      (item) => `
        <tr>
          <td style="padding:8px;border-bottom:1px solid #eee;">${item.name}</td>
          <td style="padding:8px;text-align:center;border-bottom:1px solid #eee;">${item.quantity}</td>
          <td style="padding:8px;text-align:right;border-bottom:1px solid #eee;">₱${item.price.toFixed(2)}</td>
          <td style="padding:8px;text-align:right;border-bottom:1px solid #eee;">₱${(
            item.price * item.quantity
          ).toFixed(2)}</td>
        </tr>
      `
    )
    .join("");

  const html = `
    <div style="max-width:600px;margin:auto;padding:20px;border:1px solid #ddd;border-radius:10px;font-family:Arial,sans-serif;">
      <h2 style="color:#2e7d32;text-align:center;margin-bottom:8px;">ZenTree</h2>
      <h3 style="text-align:center;margin-bottom:20px;">Receipt for Order #${orderId}</h3>
      <p style="font-size:15px;">${description}</p>

      <table style="width:100%;border-collapse:collapse;margin-top:20px;">
        <thead>
          <tr style="background:#f8f8f8;">
            <th style="text-align:left;padding:8px;">Item</th>
            <th style="padding:8px;">Qty</th>
            <th style="padding:8px;">Price</th>
            <th style="padding:8px;">Subtotal</th>
          </tr>
        </thead>
        <tbody>${itemsHTML}</tbody>
      </table>

      <h3 style="text-align:right;margin-top:15px;">Total: ₱${total.toFixed(2)}</h3>

      ${
        link
          ? `<a href="${link}" 
               style="display:inline-block;margin-top:15px;padding:10px 16px;background:#2e7d32;color:white;text-decoration:none;border-radius:4px;">
               View Receipt Online
             </a>`
          : ""
      }

      <p style="margin-top:20px;font-size:13px;color:#555;">This receipt was automatically generated by ZenTree.</p>
    </div>
  `;

  try {
    await transporter.sendMail({
      from: process.env.NODEMAILER_USER,
      to,
      subject: `ZenTree - Receipt for Order #${orderId}`,
      html,
    });

    return { success: true };
  } catch (error) {
    console.error("Send Receipt Action Error:", error);
    return { success: false };
  }
}
