import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./../../globals.css";
import "./../../globalproduct.css";
import SideProfile from "@/app/ui/profile/SideProfile";
import { Toaster } from "sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-between gap-10 w-full pt-40 pb-20 px-10">
            <SideProfile/>
            <div className="w-full bg-gray-100">
              {children}
            </div>
            <Toaster/>
        </div>
      </body>
    </html>
  );
}
